### ISSUE TITLE
Support for `requires_any` and `allow_missing` in auth filter

### ISSUE THREAD

**Issue by long1eu** [GoogleCloudPlatform/esp-v2#134]
Is there a way to mimic this configuration for jwt? More specifically I want to allow a call with JWT or not.  
Is `requires_any` and `allow_missing` supported?
```
- name: envoy.filters.http.jwt_authn
  typed_config:
    "@type": type.googleapis.com/envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication
    providers:
      firebase:
        issuer: https://securetoken.google.com/comic-run-app
        audiences:
          - "comic-run-app"
        local_jwks:
          inline_string: '{"5e9ee97c840f97e0253688a3b7e94473e528a7b5":"-----BEGIN CERTIFICATE-----\nMIIDHDCCAgSgAwIBAgIIZC7uPq+FdkIwDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE\nAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMjAw\nNDE5MDkxOTU2WhcNMjAwNTA1MjEzNDU2WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl\nbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBAN4QmiJxlOTvbw/wwJPYISofcxRXb/I4+K8noG7fFhim+RxU\n/f84uYyDssopXt6jiUGeBKMvm65fi108EfGZXCYPZVBX1dgkddRkgNA2afhvrgdF\n7BG9U1e1SPlcovJH4upn5bQb0kOr7yTg6LfihA30kgZ3RyekrSx4VJP+UNb38f+J\ntOhiROEwUOS/0J35+8jZtO5FqVfp/hxfGLMdsi+l7kA65ogW/4uQCaD8V54Ncf6D\nn0qX3qW3ze2kO1W4NDmOhLhpef8nBORs1Mt7dvKxK3QNMJQwtqqO1wQC4oKzvhNY\neNsfw+nFiDtAyUFwZOVbYP2Vsp3p3oYu1impJu0CAwEAAaM4MDYwDAYDVR0TAQH/\nBAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ\nKoZIhvcNAQEFBQADggEBAE7NhWSHuaikAo6EVt7Q4F+eOCAywQbGJgVE/xdK8AA+\nmEbU6Ybi8wc4yCE2QW2NYMH822MPiuiTKgBRPdOPQa1YrOfmvLQt0ZHGADl/d2U8\ny0wPZJWjCWHRkufPOMr2EFhwlA5Pj1mBTKn9PZAQf9rWiJuYhkb4jm6hsABmL0HY\ngGZkLcXsnzIWfNj0IXU7YRbY7ko5NoqfXe3aOoNIysgF59wInPUPnYyKZjrRS0Jj\nU93x28x7EC2clk59tRylyoJnRDbs4WbLMpzS8Fq6APa0ukHRV9cimjqmQbEJ5v6y\nTBtNG1gPXsUJQldCKMYWmXh0hAdq+ZjcRVZnOngS35Q=\n-----END CERTIFICATE-----\n","0babb22440da032c5d0042cdaa9d285cf8d202c4":"-----BEGIN CERTIFICATE-----\nMIIDHDCCAgSgAwIBAgIIN3zFmJoUjoYwDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE\nAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMjAw\nNDExMDkxOTU2WhcNMjAwNDI3MjEzNDU2WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl\nbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBAKjiZSt/6eRBHhSAWZBzfnG3oCx5DhPKqYLCOVONGkWRbJ1K\nRRbww77SH4PbRRP7kz/1jADgg9D0klW7QlD04ZXm/sUDPYwguTta5IRnOao+vyJp\nvk/XPCX2deQn+whblrhQJ5eAIos6Fd4KUNnhMQjWgzXp0k4Xnx5vFVNexp4GP1Bv\nvPppQQB+V/SBsqeL/oDpjmJiw5NSwFvexs54x9+K9vHVMrdjYSHBMEVNzVcZSHzn\n6y1a0Q3I52FUwAaqydcV+fzCW+gP/LlM9NNpio9GhotmjDZw+4BsgSU+8xyfcyR/\nowjcyG1fbgu9uQL95BaeQoPsfMRfdSXMsLZoOOcCAwEAAaM4MDYwDAYDVR0TAQH/\nBAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ\nKoZIhvcNAQEFBQADggEBAGzj/Cu2T7fHT9wvJorxV5vy0BJ+w0/H4jQET5URXcva\nK5DnPO46fbRI+ri8OhYn4X4/tOMF+HumOp+bo/me6eJYTfTIBiIrX3yoTcag/tkz\nTMKeFW7kcyptHTWOp+qzz2hezR44+JwmE4WN3yV5hoQRXpar9Hzln+rcuUi3hlRZ\nhQk2qgcBkQ/EwGYqPh7JFYriwbEOpHNJFJUMiBPVYO9MEdI0Yrs875cAF6FI8iFj\nNA1A2Mvn7rQvRtPpRQY4/NDABDvkcjPD+imyG/RKXjY+XXRjYY/Jw8YnMxcsFh81\n1N5z2VeA+n03vLqll5vgecVfjn2d+GpN4fONUQtFLN4=\n-----END CERTIFICATE-----\n"}'
        forward_payload_header: "x-endpoint-api-userinfo"
        payload_in_metadata: "jwt_payloads"
    rules:
      - match:
          prefix: "/comicrun.v1.ComicMetadata/CreateKeyInfo"
        requires:
          provider_name: firebase
      - match:
          prefix: "/comicrun.v1.ComicMetadata/UpdateKeyInfo"
        requires:
          provider_name: firebase
      - match:
          prefix: "/comicrun.v1.ComicMetadata/ListKeyInfo"
        requires:
          requires_any:
            requirements:
              - provider_name: firebase
              - allow_missing: {}
      - match:
          prefix: /
```

**Comment by qiwzhang** [comment]
Both ESPv1 and v2 only support OpenAPI 2.0 spec.  You have to use OpenAPI to specify JWT auth requirement.  It has some limitation. 

For example, it does NOT support AND.   But  It does support OR.  

You can do
```
 require: 
   jwt1 OR jwt2. 
```
But Not
```
 require: 
   jwt1 AND jwt2. 
```
Please see [detail](https://cloud.google.com/endpoints/docs/openapi/openapi-limitations#security_requirements_for_oauth2)

**Comment by long1eu** [comment]
How about gRPC?

**Comment by qiwzhang** [comment]
for gRPC, you need to directly work with Google service config Auth defined [here](https://github.com/googleapis/googleapis/blob/master/google/api/auth.proto#L71).

It only support OR for multiple `requirements`.  If you define two requirements jwt1 and jwt2 in a rule,
it means: either jwt1 OR jwt2

**Comment by long1eu** [comment]
Awesome, but how can I say `jwt` OR `no-jwt`

**Comment by qiwzhang** [comment]
What does "no-jwt" mean?  Could you elaborate your use cases?

**Comment by long1eu** [comment]
Sure. Envoy allows you to specify that an endpoint can require a jwt but will not fail if none is provided. 

https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/jwt_authn/v2alpha/config.proto#envoy-api-field-config-filter-http-jwt-authn-v2alpha-jwtrequirement-allow-missing

This is denoted by the `allow_missing` requirement.

In my current envoy config I have this:
```
      - match:
          prefix: "/comicrun.v1.ComicMetadata/ListKeyInfo"
        requires:
          requires_any:
            requirements:
              - provider_name: firebase
              - allow_missing: {}
 ```

So the JWT, if present, should match `firebase`, but if not provided the call should still go further.
