### ISSUE TITLE
ESPv2 not forwarding original Authorization header when an x-google-backend is specified

### ISSUE THREAD

**Issue by fareeda0** [GoogleCloudPlatform/esp-v2#140]
Noticed this behaviour recently.

I'm using ESPv2 as a gateway to connect multiple cloud run services. As such, I have multiple x-google-backends specified in my API spec.

As per the docs, if ESP needs to overwrite the original Authorization header, it will forward the original one in the X-Forwarded-Authorization header.

However, when I log the headers received by my cloud run services this forwarded header is missing.

Any ideas?

Thanks :)

**Comment by fareeda0** [comment]
For some more info, these are the headers received by my cloud run service. The `Authorization` header is overwritten by ESPv2 and isn't the original header send by the client (in this case Postman)

```
{
    "host": "entities-qlke7n23aa-ew.a.run.app",
    "user-agent": "PostmanRuntime/7.24.1",
    "accept": "application/json",
    "cache-control": "no-cache",
    "postman-token": "da5a4c99-b566-44f0-a351-e4eb5d92abf7",
    "x-cloud-trace-context": "9e9591b2137b514bbca7680f58a1076d/15042261411070150171",
    "x-forwarded-for": "92.236.63.50,2600:1900:2000:91::",
    "x-forwarded-proto": "https",
    "forwarded": "for=\"92.236.63.50\";proto=https,for=\"2600:1900:2000:91::\";proto=https",
    "content-length": "0",
    "x-request-id": "08d3b30d-8480-9c42-80da-b48f7a8ba16b",
    "x-endpoint-api-userinfo": "<DECODED_JWT_PAYLOAD>",
    "authorization": "Bearer <ESPV2_JWT>",
    "accept-encoding": "gzip, deflate, br"
}
```

In my OpenAPI spec, here is the corresponding path:

```
get:
        tags:
          - organisation
        x-google-backend:
            address: <REDACTED>
            protocol: h2
            path_translation: APPEND_PATH_TO_ADDRESS
        security:
          - firebase: []
        summary: List all organisations
        operationId: listOrg
        responses:
          '200':
            description: A successful response
            schema:
              type: string
```

and here is the corresponding security definition (I'm using firebase)

```
firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/<REDACTED>"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "<REDACTED>"
```
