### ISSUE TITLE
Using custom domain mapping as backend address in api config results in "invalid token" from backend service.

### ISSUE THREAD

**Issue by fratle** [GoogleCloudPlatform/esp-v2#19]
## Summary
Using custom domain mapping as backend address in api config results in "invalid token" error from backend service. Workaround it to use the domain generated by Cloud Run as backend address to make it work.

## Background
We are just getting started with Cloud Run and we wished to use our own .run domain for all our Cloud Run services. Using our custom domain makes deployment easier, because we have already planned our domain names in advance and it also simplifies service discovery since the domain names are static and predetermined.

We deployed our gRPC service, as per instructions here: https://cloud.google.com/endpoints/docs/grpc/get-started-cloud-run, but we used our custom domains instead of the auto-generated.
After deployment we got 401 from our backend service:
`The request was not authorized to invoke this service. Read more at
https://cloud.google.com/run/docs/securing/authenticating`.

After some debugging we realized that the esp service was not authorized to call
the backend service because the backend address was set to our
custom domain, see api_config.yaml. When we enabled debugging for the espv2
container the error, "invalid token", from the backend service was visible in
the logs, which are included below.

## Workaround
Use the automatically assigned domain as backend address

```
backend:
  rules:
    - selector: "*"
      address: {{cloud run assigned domain}}
```

## Config
The esp container used was:
gcr.io/endpoints-release/endpoints-runtime-serverless:2.5.0

api_config.yaml
```
type: google.api.Service
config_version: 3

name: {our domain}.dev

title: Service API
apis:
- name: service.Service

usage:
  rules:
  - selector: "service.path"
    allow_unregistered_calls: true
backend:
  rules:
    - selector: "*"
      address: grpcs://{our domain}.run
```
## Error message from esp

Error message that the esp container got from the backend service:
```
 "D0221 11:58:51.089 28 envoy] [28][http][external/envoy/source/common/http/conn_manager_impl.cc:1569] [C5][S5014636426089945857] encoding headers via codec (end_stream=false):
':status', '401'
'www-authenticate', 'Bearer error=\"invalid_token\" error_description=\"The access token could not be verified\"'
'date', 'Fri, 21 Feb 2020 11:58:50 GMT'
'content-type', 'text/html; charset=UTF-8'
'server', 'envoy'
'content-length', '337'
'x-envoy-upstream-service-time', '45'"  
```

## How to reproduce
Follow the instructions in https://cloud.google.com/endpoints/docs/grpc/get-started-cloud-run to setup the service. Use custom domain instead of the auto generated ones.
Enable debugging for the esp container.
The logs will contain the error message described above.

**Comment by TAOXUY** [comment]
Hi fratle,

Could you please double check the token esp sending to backend which you can see in debug log by [this website](https://jwt.io/) with your custom domain in the address of backend?  Is the `aud` in the form of `https://YOUR_CUSTOME_DOMAIN`?

**Comment by nareddyt** [comment]
@fratle, we spent some time discussing offline.

Could you clarify your use case for using a custom domain name? There are 2 workarounds, but these may not be ideal if you are using the custom domain name to abstract away Cloud Run URIs:

- As you described, use the generated service name

```
backend:
  rules:
    - selector: "*"
      address: grpcs://{cloud-run-domain}.run
```

- Manually set the JWT Audience to the generated service name, but still use your custom domain. [Reference](https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#backendrule)

```
backend:
  rules:
    - selector: "*"
      address: grpcs://{your-domain}.run
      jwt_audience: https://{cloud-run-domain}.run
```

I will follow up with the Cloud Run team on which audience is expected.
