### ISSUE TITLE
Proto constraint validation failed (Duplicated pattern or invalid pattern)

### ISSUE THREAD

**Issue by glassonion1** [GoogleCloudPlatform/esp-v2#254]
The following error occurs even though the URL pattern is different.
```
esp    | I0731 10:22:58.984492       6 config_manager.go:297] respond type.googleapis.com/envoy.config.listener.v3.Listener[] version "" with version "2020-07-XXr1"
esp    | W0731 10:22:59.014 19 envoy] [19][config][external/envoy/source/common/config/grpc_subscription_impl.cc:100] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) ingress_listener: Proto constraint validation failed (Duplicated pattern or invalid pattern): uri_template: \"/v1/companies/{id}/users/{user_id}\"\nhttp_method: \"OPTIONS\"
```

My gRPC service is below.
```
service UserService {
  rpc Get(GetRequest) returns (User) {
    option (google.api.http) = {
      get: "/v1/companies/{id}/users/{user_id}"
    };
  }
  rpc Update(UpdateRequest) returns (User) {
    option (google.api.http) = {
      put: "/v1/companies/{id}/users/{user.id}"
      body: "user"
    };
  }
}
```

My protobuf messages below.
```
message GetRequest {
  string id = 1;
  string user_id = 2;
}

message User {
  string id = 1;
  string name = 2;
}

message UpdateRequest {
  string id = 1;
  User user = 2;
}
```

Is there a good way to avoid this error?

**Comment by nareddyt** [comment]
Huh, that's interesting. That is not the intended behavior, it should be supported.

I'm having trouble reproducing it. But I think this only happens if you enable CORS in ESPv2 (your backend does not support it, so you let ESPv2 handle it):
- Do you have CORS configuration enabled in ESPv2? For example, are you using any of the CORS flags [documented here](https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#cors)?
- If so, can you try disabling CORS and see if it works?

**Comment by nareddyt** [comment]
Or does your backend support CORS, and you enabled `allowCors: True` under `x-google-endpoints` under your service config?

Can you temporarily delete that and see if the error still occurs? I'm fairly certain you won't see the error anymore if you do this, but I just want to confirm.

For ESPv2 engineers: The problem is that we generate an OPTIONS `HttpRule` for each API Producer configured rule. This usually works fine, unless the API Producer has operations with matching HTTP URLs but different HTTP Methods. In this case, we generate 2 `HttpRules` with matching HTTP URLS *and* matching HTTP Method of `OPTIONS`. This results in config validation failure, as Path Matcher cannot decide which operation to call it.

The fix would be to not generate duplicates, should be fairly easy. I can attempt to reproduce and fix.

**Comment by glassonion1** [comment]
I have not turned on any allowCors flag.

My docker-compose file is below.
```
version: '3.7'
services:
  center:
    container_name: sample
    build:
      context: ./sample
    ports:
      - "127.0.0.1:50051:50051"
    volumes:
      - "./sample:/work"

  esp:
    image: gcr.io/endpoints-release/endpoints-runtime:2.9
    ports:
      - "8082:8082"
    volumes:
      - "./sample:/esp"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/esp/gcp_cred.json
    depends_on:
      - sample
    command: >
      --service "sample.endpoints.sample-gcp.cloud.goog"
      --backend "grpc://docker.for.mac.localhost:50051"
      --version "${CONFIG_ID}"
      --service_account_key "/esp/gcp_cred.json"
      --listener_port 8082
      --non_gcp
```

**Comment by glassonion1** [comment]
This pattern works fine. but it is not smart solution.
```
service UserService {
  rpc Get(GetRequest) returns (User) {
    option (google.api.http) = {
      get: "/v1/companies/{id}/users/{user_id}"
    };
  }
  rpc Update(UpdateRequest) returns (User) {
    option (google.api.http) = {
      put: "/v1/companies/{id}/users/{user_id}"
      body: "user"
    };
  }
}

message GetRequest {
  string id = 1;
  string user_id = 2;
}

message User {
  string id = 1;
  string name = 2;
}

message UpdateRequest {
  string id = 1;
  User user = 2;
  string user_id = 3;
}
```

It seems to be judged as a duplicate only when the nested field is specified.
NG: user.id
OK: user_id

In my opinion, I suspect the following code is a problem.
https://github.com/GoogleCloudPlatform/esp-v2/blob/14aadff5bfd391a8dcc0eab187a5c5e6959475bf/src/envoy/http/path_matcher/filter_config.cc#L35

**Comment by nareddyt** [comment]
The code you linked (`filter_config.cc`) is where the error occurs, but this is extra validation. Our control plane is generating the config it sends to that envoy code. It should not generate duplicate configs, so our golang code is the root problem.

I have PR #255 that fixes the issue for CORS. I'm fairly certain it's related because the error you provided says `http_method: \"OPTIONS\"`. We only generate this for CORS configuration.

I realized in my previous comment I linked to an OpenAPI document, but you use gRPC. Is it possible your service configuration yaml file (not the docker compose file) for `sample.endpoints.sample-gcp.cloud.goog` has `allow_cors: true`? [Relevant gRPC documentation](https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#endpoint).

If not, can you send me your service config so I can reproduce the error you face? You can email it privately to nareddyt@google.com . Run this command:

```
gcloud endpoints configs describe "${CONFIG_ID}"
  --service="${SERVICE_NAME}" \
  --format=json \
  > service.json
```

And the full service config should be in the `service.json` file.

**Comment by glassonion1** [comment]
>The code you linked (filter_config.cc) is where the error occurs, but this is extra validation. Our control plane is generating the config it sends to that envoy code. It should not generate duplicate configs, so our golang code is the root problem.
Thanks, I understand.

My cloud endpoints yaml is below. It turned on allow_cors flag.
```
type: google.api.Service
config_version: 3

name: sample.endpoints.sample-gcp.cloud.goog
endpoints:
- name: sample.endpoints.sample-gcp.cloud.goog
  allow_cors: true

title: Sample APIs
apis:
  - name: sample.SampleService

usage:
  rules:
    - selector: "*"
      allow_unregistered_calls: true
```

This issue seems to be related to allow_cors.
