### ISSUE TITLE
No healthy upstream when developing gRPC service locally

### ISSUE THREAD

**Issue by someone1** [GoogleCloudPlatform/esp-v2#449]
I am getting the following error when trying to develop locally for a purely gRPC based service:

```
{"message":"no healthy upstream","code":503}
```

I use VSCode with Docker + WSL2 for my local development environment. I have another service, using ESPv2 for an OpenAPI service, and that works with no problem. I believe the issue is specific to running ESPv2 locally for a gRPC backend since I can run OpenAPI services with ESP locally and the gRPC service runs fine when deployed on Cloud Run.

Here is the relevant snippets of my setup:

docker-compose.yaml:
```yaml
version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace/project:cached
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock
    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8080-8085:8080-8085"
    expose:
      - "8081"
      - "8084"

  adminapi-esp:
    image: gcr.io/endpoints-release/endpoints-runtime:2.22
    user: "1000:1000"
    restart: unless-stopped
    container_name: esp
    ports:
      - "127.0.0.1:8088:8088"
    volumes:
      - gcloud:/gcloud:ro
    command:
      - "--service=service-url"
      - "--rollout_strategy=managed"
      - "--listener_port=8088"
      - "--backend=grpc://dev:8084"
      - "--service_account_key=/gcloud/application_default_credentials.json"
      - "--cors_preset=basic"
      - "--cors_allow_origin=https://admin-app:8080"
      - "--cors_allow_headers=DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-User-Agent,x-api-key,x-grpc-web"
      - "--non_gcp"
      - "--enable_debug"
      - "--generate_self_signed_cert"
      - "--backend_dns_lookup_family=v4only"
    links:
      - dev
 ```

I can communicate with my dev machine at that port from the ESP container:
```bash
$ curl -v dev:8084
*   Trying 172.18.0.7...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55f053e4af90)
* Connected to dev (172.18.0.7) port 8084 (#0)
> GET / HTTP/1.1
> Host: dev:8084
> User-Agent: curl/7.64.0
> Accept: */*
>
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 15)
* Closing connection 0
```

and with grpcurl:

```
./grpcurl -protoset /gcloud/api.pb -plaintext dev:8084 orgname.admin.v1alpha.CallService/CallName
ERROR:
  Code: Unauthenticated
  Message:
```

Here are the ESP debug logs specific to the request (excluding the final report request):
```

D1224 19:37:43.310 56 envoy] [56][jwt]Called Filter : onDestroy
D1224 19:37:43.310 56 envoy] [56][filter]Called ServiceControl Filter : onDestroy
D1224 19:37:43.310 56 envoy] [56][http2][C19] stream closed: 0
D1224 19:37:43.314 56 envoy] [56][http][C19] new stream
D1224 19:37:43.314 56 envoy] [56][http][C19][S3006011801661615231] request headers complete (end_stream=false):\n\':method\', \'POST\'\n\':authority\', \'localhost:8088\'\n\':scheme\', \'https\'\n\':path\', \'/orgname.admin.v1alpha.CallService/CallName\'\n\'content-length\', \'5\'\n\'pragma\', \'no-cache\'\n\'cache-control\', \'no-cache\'\n\'authorization\', \'Bearer <REMOVED>\'\n\'x-grpc-web\', \'1\'\n\'user-agent\', \'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36\'\n\'x-api-key\', \'<REMOVED-API_KEY>\'\n\'content-type\', \'application/grpc-web+proto\'\n\'accept\', \'*/*\'\n\'origin\', \'https://admin-app:8080\'\n\'sec-fetch-site\', \'cross-site\'\n\'sec-fetch-mode\', \'cors\'\n\'sec-fetch-dest\', \'empty\'\n\'referer\', \'https://admin-app:8080/\'\n\'accept-encoding\', \'gzip, deflate, br\'\n\'accept-language\', \'en-US,en;q=0.9\'

D1224 19:37:43.314 56 envoy] [56][jwt]Called Filter : setDecoderFilterCallbacks
D1224 19:37:43.315 56 envoy] [56][jwt]Called Filter : decodeHeaders
D1224 19:37:43.315 56 envoy] [56][jwt]extract authorizationBearer 
D1224 19:37:43.315 56 envoy] [56][jwt]extract x-goog-iap-jwt-assertion
D1224 19:37:43.315 56 envoy] [56][jwt]auth0: JWT authentication starts (allow_failed=false), tokens size=1
D1224 19:37:43.315 56 envoy] [56][jwt]auth0: startVerify: tokens size 1
D1224 19:37:43.315 56 envoy] [56][jwt]auth0: Parse Jwt <REMOVED>
D1224 19:37:43.315 56 envoy] [56][jwt]auth0: Verifying JWT token of issuer https://<REMOVED>.auth0.com/
D1224 19:37:43.315 56 envoy] [56][jwt]auth0: JWT token verification completed with: OK
D1224 19:37:43.315 56 envoy] [56][jwt]Jwt authentication completed with: OK
D1224 19:37:43.315 56 envoy] [56][filter]Called ServiceControl Filter : decodeHeaders
D1224 19:37:43.315 56 envoy] [56][filter]get operation_name: orgname.admin.v1alpha.CallService.CallName
D1224 19:37:43.315 56 envoy] [56][filter]Sending check : service_name: \"service-url\"\noperation {\n  operation_id: \"ebbad646-39c3-4efb-bc6a-e6bee0b78404\"\n  operation_name: \"orgname.admin.v1alpha.CallService.CallName\"\n  consumer_id: \"api_key:<REMOVED-API_KEY>\"\n  start_time {\n    seconds: 1608838663\n    nanos: 315386900\n  }\n  end_time {\n    seconds: 1608838663\n    nanos: 315386900\n  }\n  labels {\n    key: \"servicecontrol.googleapis.com/caller_ip\"\n    value: \"172.18.0.1\"\n  }\n  labels {\n    key: \"servicecontrol.googleapis.com/referer\"\n    value: \"https://admin-app:8080/\"\n  }\n  labels {\n    key: \"servicecontrol.googleapis.com/service_agent\"\n    value: \"ESPv2/2.22.0\"\n  }\n  labels {\n    key: \"servicecontrol.googleapis.com/user_agent\"\n    value: \"ESPv2\"\n  }\n}\nservice_config_id: \"2020-12-24r0\"

D1224 19:37:43.315 56 envoy] [56][router][C19][S3006011801661615231] cluster \'backend-cluster-adminapi-service.dev.project.com:443\' match for URL \'/orgname.admin.v1alpha.CallService/CallName\'
D1224 19:37:43.315 56 envoy] [56][http][C19][S3006011801661615231] Sending local reply with details no_healthy_upstream
D1224 19:37:43.315 56 envoy] [56][filter]Filter::encodeHeaders is called.
D1224 19:37:43.315 56 envoy] [56][http][C19][S3006011801661615231] encoding headers via codec (end_stream=false):\n\':status\', \'503\'\n\'content-length\', \'45\'\n\'content-type\', \'application/grpc-web+proto\'\n\'access-control-allow-origin\', \'https://admin-app:8080\'\n\'access-control-expose-headers\', \'Content-Length,Content-Range\'\n\'date\', \'Thu, 24 Dec 2020 19:37:43 GMT\'\n\'server\', \'envoy\'

D1224 19:37:43.315 56 envoy] [56][http][C19][S3006011801661615231] doEndStream() resetting stream
D1224 19:37:43.315 56 envoy] [56][http][C19][S3006011801661615231] stream reset
D1224 19:37:43.315 56 envoy] [56][filter]Called ServiceControl Filter : log
```
