### ISSUE TITLE
Persistent self signed certificates

### ISSUE THREAD

**Issue by someone1** [GoogleCloudPlatform/esp-v2#470]
This may be more of user (_me_) issue, but I'm struggling to get the `--generate_self_signed_cert` to store the certificates persistently while developing locally.

Specifically, when creating a volume to mount into `/tmp/ssl/endpoints/` - the mount RW permissions are tied to `root` but the ESP service launches as the `envoy` (UID/GID 999) user which cannot write to the directory and puts ESP in an endless crash loop.

I think my choices are to override the user to be root for the container, generate the certificates myself and them mount those, or the path needs to pre-exist with RW permission set to the `envoy` user in the container.

I think if having the directory pre-exist with the correct permissions fixes the issue, it'd be the ideal solution. Any thoughts on if this would work and if it'd be something you all are open to?

**Comment by qiwzhang** [comment]
If you want to persistently store self-signed certificates, I would suggest you don't use `--generate_self_signed_cert` flag.  You can run the openssl command outside of ESP container and mount the volume to ESP and use flag `--ssl_server_cert_path` to specify its path.

**Comment by someone1** [comment]
I was thinking that'd be the response - it would be simpler to distribute this across my team as working out of the box vs trying to get them all to do this generation setup first - though it's definitely not a show stopper.

Thank you for the consideration!

**Comment by nareddyt** [comment]
If I understand correctly, all we need to do is create the directory (with correct permissions) when building the docker image. 

It should be simple. Since @someone1 has a valid use-case, we can support it. @qiwzhang is there any concern with this? We'd much rather have the directory with correct permissions than the user modifying the `envoy` user to root.

Ref:
- Cert generation: https://github.com/GoogleCloudPlatform/esp-v2/blob/3892b9e2413fc8e23050bd8bd230b7723677b00b/docker/generic/start_proxy.py#L901
- Dockerfile: https://github.com/GoogleCloudPlatform/esp-v2/blob/3892b9e2413fc8e23050bd8bd230b7723677b00b/tests/integration_test/opencensus_tracing_test.go#L506

**Comment by qiwzhang** [comment]
Not, the issue is: users want to mount an external folder,  allow container user `envoy` to read+write to that folder.   Such the files in the folder can be persistent over container re-start.

**Comment by someone1** [comment]
to give context, i just wanted persistent certs so it doesn't keep getting flagged as untrusted on my local. every ESP restart I need to accept the new certs. I actually don't think this will work as I wanted since `--generate_self_signed_cert` ignores the fact that certs may already exist in `/tmp/ssl/endpoints/` - not sure why I thought it'd behave differently.

TIL I could easily just extend the container myself w/ Docker compose as follows:

```Dockerfile
# Dockerfile.esp
FROM gcr.io/cloudesf-testing/apiproxy:333f22f690774690e4dc7d9becb7807c24d49e60

RUN mkdir -p /tmp/ssl/endpoints && chmod 0777 /tmp/ssl/endpoints
```

```yaml
# docker-compose.yml

version: "3"
services:
 dev: # omitted
 adminapi:
    build:
      context: .
      dockerfile: Dockerfile.esp
    restart: unless-stopped
    ports:
      - "127.0.0.1:8088:8088"
    volumes:
      - gcloud:/gcloud:ro
      - ssl:/tmp/ssl/endpoints
    command:
      - "--service=REMOVED"
      - "--rollout_strategy=managed"
      - "--listener_port=8088"
      - "--backend=grpc://dev:8084"
      - "--enable_backend_address_override"
      - "--service_account_key=/gcloud/application_default_credentials.json"
      - "--cors_preset=basic"
      - "--cors_allow_origin=https://admin-app:8082"
      - "--cors_allow_headers=DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-User-Agent,x-api-key,x-grpc-web"
      - "--non_gcp"
      - "--enable_debug"
      - "--generate_self_signed_cert"
    links:
volumes:
    gcloud
    ssl
```

I'm not sure if there's anything to do here, so apologies for the confusion.
