### ISSUE TITLE
Configure Cloud Endpoints to proxy traffic to a Cloud Run multiplexed (gRPC|HTTP) service

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/esp-v2#523]
Is it possible to configure Cloud Endpoints to proxy (HTTP|gRPC) traffic to a mutiplexed backend?

I'd like to use Cloud Run to host a backend gRPC service. Cloud Run only permits publication of a single port. To overcome this limitation, the service uses [cmux](https://github.com/soheilhy/cmux) to multiplex gRPC (HTTP/2 and `application/grpc`) and HTTP (HTTP/1 for Prometheus metrics) traffic.

This works when the service is deployed to Cloud Run without the proxy.

I'd like to use Cloud Endpoints (API management, auth) to proxy traffic to the Cloud Run backend.

It's unclear to me how I could configure ESPv2 to route both the gRPC and the non-gRPC traffic to the service.

```golang
grpcServer := grpc.NewServer()

httpServer := &http.Server{
	Handler: promhttp.Handler(),
}

m := cmux.New(listen)

grpcListen := m.MatchWithWriters(
	cmux.HTTP2MatchHeaderFieldSendSettings("content-type", "application/grpc"),
)
httpListen := m.Match(cmux.HTTP1Fast())

go grpcServer.Serve(grpcListen)
go httpServer.Serve(httpListen)

m.Serve()
```

Is this possible?

Any pointers even if only high-level guidance would be appreciated, thank you!

**Comment by qiwzhang** [comment]
We have not tried "cmux",  not sure how it works.  There are two options you can try:
1) assume cmux can handle the http1 requests carried over from http2 connections.  We can use ESPv2 envoy to convert http1 requests to http2.  The backend address will use "grpcs://cloud_function_host" to use http2 connection to talk to backend cmux server for both gRPC and http1.   It may works.

2) if above fail,  you need a different path prefix to distinguish http1, gRPC requests.  e.g. /Service_name/* for GRPC requests and /metrics/* for http1 requests.  set x-google-backend.address with "grpcs://cloud_function_host" for grpc requests and "https://cloud_function_host" for http1 requests.  ESPv2 will setup http2 connections for gRPC and http1 connections for http1.

**Comment by DazWilkin** [comment]
@qiwzhang you're awesome, thank you! This is very helpful.

I'll try option 1 and I'd not considered (and it's a good idea) option 2.

I'll report back in the next few days when I try this, thank you!

**Comment by DazWilkin** [comment]
OK, I have some success but can't yet access both gRPC and HTTP/1 Prometheus metrics.

I can access both gRPC and Prometheus metrics against my backend (`SRV_HOST`):

```bash
grpcurl \
-H "Authorization: Bearer $(gcloud auth print-identity-token)" \
-d "{\"customer_id\": \"${ID}\"}" \
-proto something.proto \
${SRV_HOST}:443 v1alpha1.Something/CustomerGet
{
  "customer": {
    "name": "...",
    "domainName": "..."
  }
}
```
And:
```bash
curl \
--silent \
--request GET \
--write-out '%{response_code}' \
--output /dev/null \
https://${SRV_HOST}:443/metrics
200
```

> **NOTE** And I'm getting valid metrics

Demonstrating that the backend service works as expected.

And, if I deploy only gRPC to the proxy:

```bash
gcloud endpoints services deploy something.pb something.yaml \
--project=${PROJECT}

./cloud_build_image ...

gcloud run deploy ...
```

I can gRPCurl the gRPC service through the proxy (`ESP_HOST`):

```bash
grpcurl \
-H "Authorization: Bearer $(gcloud auth print-identity-token)" \
-d "{\"customer_id\": \"${ID}\"}" \
-proto something.proto \
${ESP_HOST}:443 v1alpha1.Something/CustomerGet
{
  "customer": {
    "name": "...",
    "domainName": "..."
  }
}
```

Or (!) I can deploy the OpenAPI specifying the Prometheus metrics endpoint (`/metrics`):

```bash
gcloud endpoints services deploy prometheus.yaml \
--project=${PROJECT}

./cloud_build_image ...

gcloud run deploy ...
```

I can `GET` the metrics:

```bash
curl \
--silent \
--request GET \
--write-out '%{response_code}' \
--output /dev/null \
https://${ESP_HOST}:443/metrics
200
```

Demonstrating that the proxy can be deployed to route to the gRPC backend correctly **or** to the Prometheus metrics.

But, if I try to deploy both the gRPC config and the Prometheus config:

```bash
gcloud endpoints services deploy something.pb something.yaml prometheus.yaml \
--project=${PROJECT}
```

I get errors:

```bash
ERROR: (gcloud.endpoints.services.deploy) HttpError accessing <https://servicemanagement.googleapis.com/v1/services/${ESP_HOST}/configs:submit?alt=json>: response: <{'x-debug-tracking-id': '5765010803531470195;o=0', 'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Fri, 04 Jun 2021 18:08:44 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'transfer-encoding': 'chunked', 'status': 500}>, content <{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
>
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach.
```

**Comment by DazWilkin** [comment]
I just reread your guidance and noticed: "The backend address will use grpcs://cloud_function_host ... for both gRPC and http1"

Trying that.

**Comment by qiwzhang** [comment]
You may have to combine something.yaml prometheus.yaml manually.

**Comment by DazWilkin** [comment]
Similar error:

```bash
ERROR: (gcloud.endpoints.services.deploy) HttpError accessing <https://servicemanagement.googleapis.com/v1/services/${ESP_PROXY}configs:submit?alt=json>: response: <{'x-debug-tracking-id': '14684621501479235959;o=0', 'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Fri, 04 Jun 2021 18:45:56 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'transfer-encoding': 'chunked', 'status': 500}>, content <{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
>
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach.
```

I'm assuming you may be able to trace using the `x-debug-tracking-id` values.

**Comment by qiwzhang** [comment]
No, I could not.   We need ServiceManagement team on-call to track it. But they need your service config ${ESP_PROXY}

It is rare to provide two independent yaml files in "gcloud endpoints services deploy".  I suspected  you may have to combine them into one manually.

**Comment by DazWilkin** [comment]
I'll email you the value.

I'll try merging the config files into one.

> ironically I got the idea from Google's documentation (and now, of course, I can't find that link).

**Comment by DazWilkin** [comment]
Combining results in the same error but perhaps highlights the possible issue. Namely, the gRPC service uses `google.api.Service` whereas the Prometheus metrics (I've tried to define) uses OpenAPI, and there's no obvious way perhaps for service management to disambiguate the intent.

Conceptually, envoy can, of course, handle this type of configuration but perhaps I'm expecting too much of Cloud Endpoints this way in being able to parse my files into an appropriate configuration?

**Comment by qiwzhang** [comment]
Yes, it is NOT easy to combine a gRPC service spec (in Google.api.Service) with an OpenAPI spec. But it is easier to combine two Google.api.service spec.   You can convert OpenAPI spec into Google.api.service first by:
* gcloud endpoints services deploy OpenAPI
* then download it by "gcloud endpoints configs describe CONFIG_ID --service=SERVIC_NAME".

 That will be the google.api.service format.

**Comment by DazWilkin** [comment]
Aha! I will try that

**Comment by DazWilkin** [comment]
And, it sounds like I'm not the first to try this which is reassuring!

**Comment by qiwzhang** [comment]
Sorry, you are the FIRST trying to support both gRPC service and HTTP service

**Comment by DazWilkin** [comment]
I like to pioneer :-)

Found a bug: https://github.com/GoogleCloudPlatform/esp-v2/issues/528

**Comment by DazWilkin** [comment]
I'm unsure how to represent the REST API as a `google.api.Service`

This is the mashup of the original gRPC service and the `gcloud endpoints config describe` Prometheus service:

```YAML
type: google.api.Service
config_version: 3
name: proxy-g2yk7vejmq-uw.a.run.app
title: Ackal Service
apis:
  - name: v1alpha1.Something
  - name: 0.proxy_[hash]_uw_a_run_app
    methods:
      - name: Metrics
        request_type_url: type.googleapis.com/google.protobuf.Empty
        response_type_url: type.googleapis.com/google.protobuf.Value
    source_context:
      file_name: something.yaml
    version: 0.0.1
usage:
  rules:
    - selector: "*"
      allow_unregistered_calls: true
backend:
  rules:
    - selector: "v1alpha1.Something.*"
      address: grpcs://backend-[hash]-uw.a.run.app:443
    - selector: 0.proxy_[hash]_uw_a_run_app.Metrics
      address: https://backend-[hash]-uw.a.run.app:443
```

There are 2 `apis`, the original gRPC and the new one for the OpenAPI. This is the ESP host name, prefixed with `0.` and with hyphens replaced by underscores.

This then appears in `backend` with `.Metrics` appended

But, when I try to deploy, I get:

```bash
ERROR: (gcloud.endpoints.services.deploy) INVALID_ARGUMENT: Cannot convert to service config.
'location: "combined.yaml:7"
kind: ERROR
message: "Cannot resolve api \'0.proxy_[hash]_uw_a_run_app\'."

 location: "combined.yaml:23"
message: "backend rule has selector(s) \'0.proxy_[hash]_uw_a_run_app.Metrics\' that do not match and are not shadowed by other rules."
'
```

There's a bunch of `enums`, `types`, metrics` etc. that I think I can omit (?)

**Comment by qiwzhang** [comment]
In the combine yaml,  could you try:
* for `apis` field,  only keep the one from grpc
* add http.rules like [this](https://cloud.google.com/endpoints/docs/grpc/transcoding#configuring_transcoding_in_yaml)   for your open api paths
* remove all these metrics from downloaded 
* for backend rules. try this
 ```
    backend:
      - rules: 
          - selector; "*"
            address::grpcs:://backend-[hash]-uw.a.run.app:443
```

Actually, use "*" for all selector,  it will expand to all selector when deployed

**Comment by qiwzhang** [comment]
I means for all "rules" with expanded selectors ,   remove them, and only keep one, and change its value to "*".

**Comment by DazWilkin** [comment]
I tried:

```YAML
type: google.api.Service
config_version: 3
name: ${ESP_HOST}
title: Ackal Service
apis:
  - name: v1alpha1.Something
usage:
  rules:
    - selector: "*"
      allow_unregistered_calls: true
http:
  rules:
    - selector: "*"
      get: "/metrics"
backend:
  rules:
    - selector: "*"
      address: grpcs://${ESP_HOST}:443
```

This `gcloud_build_image` but doesn't deploy to Cloud Run:

```console
Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable
```

Which is Cloud Run's generic "broken" response (I'll grab the logs) and I suspect is because my config although valid (deployed) is invalid at runtime.

**Comment by qiwzhang** [comment]
Most likely.  I spot a error here,  for http.rules, you should not use "*" for selector, you can try

```
http:
  rules:
    - selector: some_server.get_metrics
      get: "/metrics"
```

**Comment by DazWilkin** [comment]
I literally used `some_server.get_metrics` (was that what you intended?).

This gives me 404s on the HTTP GET `/metrics`(gRPC calls work).

Do I need to create a stub for this method in the gRPC service's proto?

[Using gRPC API Service Configuration](https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#using-grpc-api-service-configuration) shows a gRPC method name being mapped to e.g. `/metrics` and, in my case, there's no matching method in the gRPC proto.

I'm going to take my dog for a swim.

I **really** appreciate all your help.

If you have additional suggestions, I can try them over the weekend.

Otherwise, it would be really terrific if I could get this to work.

**Comment by qiwzhang** [comment]
Not sure who reject it with 404.  It it is ESPv2,  then the config is still not correct.   It means "GET /metrics" is not in the service config.  

If it is jected by the backend,  then option 1 doesn't work.   Envoy is using the same http2 connection to send gRPC and http1 requests to your backend. I am not sure how cmux work,  I guess  "cmux" server may need different tcp connections, grpc and http1 could not share the same tcp connection.

**Comment by qiwzhang** [comment]
If the latter, you can try to setup two types of backend rules

```
backend:
  rules:
    - selector: grpc_service.grpc_method
      address: grpcs://${ESP_HOST}:443
    - selector: http_service.get_metrics
      address: https://${ESP_HOST}:443

```

Hopefully, ESPv2 will create two envoy clusters and create separate TCP connections.

But I just checked our [code](https://github.com/GoogleCloudPlatform/esp-v2/blob/f56e54a373c8eef40ad9e30f837ec8fb2f0f160e/src/go/configinfo/service_info.go#L510) ,   we group the clusters by "host:port", not by "scheme://host:port".   So ESPv2 will not create two envoy clusters. 

Well,  it is not supported for your case. Sorry.

**Comment by DazWilkin** [comment]
The `404` is generated by ESPv2.

```bash
SERVICE="proxy"
FILTER="resource.type=\"cloud_run_revision\" "\
"resource.labels.service_name=\"${SERVICE}\" "\
"httpRequest.status=404 "\
"trace=\"projects/${PROJECT}/traces/67a4d6b4b830945816e28b950c90f3e9\""
gcloud logging read \
"${FILTER} \
--project=${PROJECT}
---
httpRequest:
  latency: 2.115177250s
  protocol: HTTP/1.1
  remoteIp: 66.235.10.167
  requestMethod: GET
  requestSize: '1220'
  requestUrl: https://proxy-[hash]-uw.a.run.app/metrics
  responseSize: '834'
  serverIp: 216.239.36.53
  status: 404
  userAgent: curl/7.68.0
insertId: 60bbbcb2000ecb844333590e
labels:
  instanceId: 00bf4bf02d33bd2ccb5d04373248620f56586b584941de4e163b3dc9915c7eff8bbd013b3990d2c092fd5ae34d66630dc5b64aa27f94cbc26949
logName: projects/${PROJECT}/logs/run.googleapis.com%2Frequests
receiveTimestamp: '2021-06-05T18:04:34.973691532Z'
resource:
  labels:
    configuration_name: proxy
    location: us-west1
    project_id: ${PROJECT}
    revision_name: proxy-00002-jev
    service_name: proxy
  type: cloud_run_revision
severity: WARNING
timestamp: '2021-06-05T18:04:34.969604Z'
trace: projects/ackal-210601/traces/67a4d6b4b830945816e28b950c90f3e9
```

And, no `404`'s from the backend:

```bash
SERVICE="..." # Backend
gcloud logging read "${FILTER}" --project=${PROJECT}
```

**Comment by DazWilkin** [comment]
```bash
gcloud endpoints configs describe ${CONFIG} \
--service=${ESP_HOST} \
--project=${PROJECT}
```
Yields:

```YAML
apis:
- methods:
  - name: SomeMethod
    requestTypeUrl: type.googleapis.com/v1alpha1.SomeMethodRequest
    responseTypeUrl: type.googleapis.com/v1alpha1.SomeMethodResponse
  - name:  ...
  name: v1alpha1.Ackal
  sourceContext:
    fileName: some.proto
  syntax: SYNTAX_PROTO3
  version: v1alpha1
authentication: {}
backend:
  rules:
  - address: grpcs://backend-[hash]-uw.a.run.app:443
    selector: v1alpha1.SomeService.SomeMethod
  - address: ...  
configVersion: 3
control:
  environment: servicecontrol.googleapis.com
documentation:
  rules:
  - description: ...
    selector: v1alpha1.SomeService.SomeMethod
  - description: ...
endpoints:
- name: proxy-g2yk7vejmq-uw.a.run.app
http: {}
id: 2021-06-05r0
logging:
logs:
metrics:
monitoredResources:
monitoring:
name: proxy-[hash]-uw.a.run.app
producerProjectId: ackal-210601
systemParameters: {}
title: Something Service
```
> **NOTE** `http` is null corroborating your hypothesis that the config remains incorrect

**Comment by DazWilkin** [comment]
One aspect I find curious is that if I deploy a valid OpenAPI spec and then get it as a `google.api.Service` (and correct the YAML keys), I'm unable to deploy the service.

I wonder whether, if I were able to get this to deploy as a Service, I'd be able to define a composite Service that included both the `GET /metrics` and the gRPC methods:

OpenAPI (`prometheus.yaml`)I:
```YAML
swagger: "2.0"
info:
  title: Prometheus
  description: "Prometheus metrics"
  version: "0.0.1"
host: proxy-[hash]-uw.a.run.app
schemes:
  - https
produces:
  - "application/json"
x-google-backend:
  address: https://backend-[hash]-uw.a.run.app:443
  protocol: "h2"
paths:
  "/metrics":
    get:
      summary: Prometheus metrics endpoint
      operationId: metrics
      responses:
        "200":
          description: Success
          schema:
            type: string
        "400":
          description: Failure
```
This deploys:

```bash
gcloud endpoints services deploy prometheus.yaml --project=${PROJECT}
```

But if I get then munge the `configs describe`:
```bash
gcloud endpoints configs describe ${CONFIG} \
--service=${ESP_HOST} \
--project=${PROJECT} \
| munge
```
I get `google.api.Service`:

```YAML
title: Prometheus
name: proxy-[hash]-uw.a.run.app
type: google.api.Service
config_version: 3
apis:
  - name: 0.proxy_g2yk7vejmq_uw_a_run_app
    methods:
      - name: Metrics
        request_type_url: type.googleapis.com/google.protobuf.Empty
        response_type_url: type.googleapis.com/google.protobuf.Value
    source_context:
      file_name: prometheus.yaml
    version: 0.0.1
usage:
  rules:
    - allow_unregistered_calls: true
      selector: 0.proxy_[hash]_uw_a_run_app.Metrics
http:
  rules:
    - get: /metrics
      selector: 0.proxy_[hash]_uw_a_run_app.Metrics
backend:
  rules:
    - address: https://backend-[hash]-uw.a.run.app:443
      jwt_audience: https://backend-[hash]-uw.a.run.app:443
      path_translation: APPEND_PATH_TO_ADDRESS
      protocol: h2
      selector: 0.proxy_[hash]_uw_a_run_app.Metrics
```
Deploying it (which should be functionally equivalent?):
```bash
gcloud endpoints services deploy prometheus.service.yaml --project=${PROJECT}
```
Yields:
```bash
location: "prometheus.service.yaml:6"
kind: ERROR
message: "Cannot resolve api \'0.proxy_[hash]_uw_a_run_app\'."

location: "prometheus.service.yaml:17"
message: "usage rule has selector(s) \'0.proxy_[hash]_uw_a_run_app.Metrics\' that do not match and are not shadowed by other rules."

location: "prometheus.service.yaml:28"
message: "backend rule has selector(s) \'0.proxy_[hash]_uw_a_run_app.Metrics\' that do not match and are not shadowed by other rules."

location: "prometheus.service.yaml:21"
message: "http rule has selector(s) \'0.proxy_[hash]_uw_a_run_app.Metrics\' that do not match and are not shadowed by other rules."
```

It appears to balk at the `apis.name` (`0.proxy_g2yk7vejmq_uw_a_run_app`) but I've included all occurrences of this from the generated `google.api.Service` (and so can't be missing a definition) and I'm unable to determine what this should be were I to generate the Service from scratch for an OpenAPI?
