### ISSUE TITLE
Include matched path header

### ISSUE THREAD

**Issue by Ulisesnama** [GoogleCloudPlatform/esp-v2#524]
Is it possible to configure Cloud Endpoints to include matched path result in headers?

We'd like to use the lookup_result from PathMatcher in our backend service. It's unclear to me how I could configure ESPv2 to get it and set as header parameter.

**Comment by qiwzhang** [comment]
ESPv2 is using Envoy RouteMatch (including PathMatcher) to match patch and apply config.  The matched result is call `operation_name" as a string.  There is a map of `operation_name` to config in the filter_config we will apply.  

Do you want to receive such `operation_name` in the headers?   It may not mean anything for you.

**Comment by Ulisesnama** [comment]
@qiwzhang We're developing a permissions system where each endpoint has one-to-one relationship with a permission. We need the matched result to get this permission and check whether or not the user has access to an endpoint.

**Comment by Ulisesnama** [comment]
Yes, we want to receive `operation_name` in the headers but we don't  know how to do it.

**Comment by qiwzhang** [comment]
We can add a flag to add `operation_name` into the headers.

**Comment by Ulisesnama** [comment]
Thank you! We appreciate that very much. 

It would be something as if I had my path configuration
```yml
/v1/permissions/{permission_id}:
  get:
    parameters:
      - in: path
        name: permission_id
        type: string
        required: true
        description: "User permission id"
```
The header would be something like this?
```
key = some_name
value = "/v1/permissions/{permission_id}"
```

This would be in the upcoming release? When is it?

**Comment by qiwzhang** [comment]
Not exactly.  The `operation_name` is the `selector` in the endpoint service config. 

If you use "gcloud endpoints service deploy ..." to push the confit to Google,  then you can output its config by CLI "gcloud endpoints configs describe CONFIG_ID --service=SERVICE_NAME"

For OpenAPI spec.  The `selector` format is `1.under_scored_service_name.operation_id`.   e.g.

```
host: examples.endpoints.your-project-id.cloud.goog
paths:
  /v1/permissions/{permission_id}:
     get:
       description: "User permission id"
       operationId: getByPermissionId,
       parameters:
         - in: path
           name: permission_id
           type: string
           required: true
          description: "User permission id"
```

The `operation_id` is:  `1.examples_endpoints_your_project_id_cloud_goog.getByPermissionId`.

The last portion is extracted from "operationId" field for a http method.   If "operationId" is not specified,  I am not sure what it is,  you can test it out.
