### ISSUE TITLE
`gcloud endpoints configs describe` YAML does not match spec

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/esp-v2#528]
The YAML|JSON returned by this service does not match the spec [google.protobuf.Method](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Method)

```bash
gcloud endpoints configs describe ${CONFIG} \
--project=${PROJECT} \
--service=${SERVICE} \
--format=yaml
```

> **NOTE** `--format=YAML` is optional; default to YAML

```YAML
apis:
- methods:
  - name: Metrics
    requestTypeUrl: type.googleapis.com/google.protobuf.Empty
    responseTypeUrl: type.googleapis.com/google.protobuf.Value
  name: ...
  sourceContext: ...
```

Also JSON (`--format=json`):

```JSON
{
  "apis": [
    {
      "methods": [
        {
          "name": "Metrics",
          "requestTypeUrl": "type.googleapis.com/google.protobuf.Empty",
          "responseTypeUrl": "type.googleapis.com/google.protobuf.Value"
        }
      ],
      "name": "...",
      "sourceContext": {},
      "version": "0.0.1"
```

These should be `request_type_url` and `response_type_url`, etc. etc.

I believe (!) these errors are a result of incorrect marshaling from protobufs.

The issue is addressed for JSON with [protojson](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) and specifically:

```golang
protojson.MarshalOptions{
	UseProtoNames: true,
}.Marshal(pb.Something)
```
