### ISSUE TITLE
CORS requests forwarded to backend 

### ISSUE THREAD

**Issue by MoSehsah** [GoogleCloudPlatform/esp-v2#570]
Hi Community,

I'm using ESP-V2 on Cloud Run and my backend is GAE Standard.

So, in my OpenAPI Specification, I provided the following on the top level

```
x-google-backend:
    address: https://<PROJECT>.nw.r.appspot.com
    jwt_audience: <JWT_ID>.apps.googleusercontent.com
    protocol: h2
```

In my ESP Build I'm using the following flag 
`--set-env-vars=ESPv2_ARGS=^++^--cors_preset=basic++--cors_allow_origin=* `

However, I'm still receiving the preflight request (`OPTIONS`) in my GAE backend. 

Is this the expected behavior? I got the understanding from this [link](https://cloud.google.com/endpoints/docs/openapi/support-cors) that CORS requests will be forwarded only if I specify `  allowCors: True` which I didn't provide since I'm not using `x-google-endpoints` anyway. What am I missing here? 

Thanks
