### ISSUE TITLE
x-google-jwt-location two entries for a single header

### ISSUE THREAD

**Issue by TAOXUY** [GoogleCloudPlatform/esp-v2#594]
https://github.com/cloudendpoints/esp/issues/850

**Comment by td-gonzales** [comment]
Sure. Is this an issue or expected behavior? 

I tried to use regex but it seems to process it as a string and doesn't evaluate regex.

**Comment by qiwzhang** [comment]
It should work by reading the extractor code [here](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/jwt_authn/extractor.cc#L248)

With your following configures:
```
    x-google-jwt-locations:
      - header: "Authorization"
        value_prefix: "Bearer "
      - header: "Authorization"
         value_prefix: ""
```

If you have a header "Authorization: Bearer TOKEN", it will extract two tokens "TOKEN" and "Bearer TOKEN".

**Comment by td-gonzales** [comment]
With that configuration this is what I'm seeing. 

```
> curl https://api-gw-7ja8lqr1.uc.gateway.dev/functionSecured -H "Authorization: Bearer `python generateJWT.py`" | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    55  100    55    0     0     11      0  0:00:05  0:00:04  0:00:01    11
{
  "message": "Jwt header is an invalid JSON",
  "code": 401
}
```

So this isn't working.

**Comment by qiwzhang** [comment]
Hmm,   we never tested with such config:
```
    x-google-jwt-locations:
      - header: "Authorization"
        value_prefix: "Bearer "
      - header: "Authorization"
         value_prefix: ""
```

What is the motivation to config two exact same header, one with a "Bearer " prefix, and one without?  According to RFC,  you should use "Bearer " prefix.  Could you remove the one without prefix?
