### ISSUE TITLE
Receiving 401/UNATHENTICATED responses for ESPv2 Auth (gRPC)

### ISSUE THREAD

**Issue by nsadeh** [GoogleCloudPlatform/esp-v2#602]
Description: 

I configured auth for ESPv2 per https://cloud.google.com/endpoints/docs/grpc/authenticating-users using Firebase. Here is my api_config.yml:
```yaml
type: google.api.Service
config_version: 3

name: gateway-<HASH>.a.run.app

title: Cloud Endpoint + Cloud Run gRPC

apis:
  - name: com.company.userroles.UserRoleService
  - name: com.company.clients.ClientService
authentication:
  providers:
  - id: firebase
    jwks_uri: https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com
    issuer: https://securetoken.google.com/<firebase-id>
    audiences: "<firebase-id>"
      # Optional.
      # jwt_locations:
      # # expect header "jwt-header-foo": "jwt-prefix-foo<TOKEN>"
      # - header: "jwt-header-foo"
      #   value_prefix: "jwt-prefix-foo"
      # - query: "jwt_query_bar"
  rules:
  - selector: "*"
    requirements:
      - provider_id: firebase
usage:
  rules:
  - selector: com.company.userroles.UserRoleService.checkStatus
    allow_unregistered_calls: true
backend:
  rules:
    - selector: "*"
      address: grpcs://<backend-address>run.app
```

Sample code:
```typescript
return await firebase.auth().currentUser?.getIdToken()
    .then(token => {
      // just for debugging
      console.log(`Retrieved user token: ${token}`);
      return token;
    })
    .then(token => {return { "authorization": `Bearer ${(token)}` }; })
    .then(metadata => stub.createClient(request, metadata))
    .then(uid => {
      console.log(`Retrieved user ID ${uid.getUserid}`);
      return uid
    })
    .catch(err => {
      console.error("Failed to make the create request");
      console.error(err)
    })
```

the gateway service (Cloud Run) has `allUsers` as an invoker. I can see the authorization header in the request data in the network tab. For the response, I get
```
{"message":"UNAUTHENTICATED:Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.","code":401}
```
preflight finishes successfully.

Some server-side logs:
```
jsonPayload: {
api_key_state: "NOT CHECKED"
api_method: "com.company.clients.ClientService.CreateClient"
api_name: "com.company.clients.ClientService"
api_version: "v1"
error_cause: "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API."
http_status_code: 401
location: "us-east1"
log_message: "com.company.clients.ClientService.CreateClient is called"
producer_project_id: "<project-id>"
response_code_detail: "service_control_bad_request{MISSING_API_KEY}"
service_agent: "ESPv2/2.30.2"
service_config_id: "2021-09-14r1"
timestamp: 1631590202.9310098
}
```
