### ISSUE TITLE
Two authentication types to the same method

### ISSUE THREAD

**Issue by vgmartinez** [GoogleCloudPlatform/esp-v2#651]
hi,
I want to configure one method (POST) with two authentication method firebase_auth and api_key, I use this config but I getting the same error that a I need a Jwt token even if a send a request with the api_key, it seems that the firebase_auth takes precedence.

```
 post:
      summary: Get a temporal serie for forecast
      operationId: get_forecast_serie
      x-google-backend:
        address: https://europe-west3-saasbcn-98ce0.cloudfunctions.net/FnQueryApi
        path_translation: APPEND_PATH_TO_ADDRESS
        protocol: h2
      security:
        - api_key: []
        - firebase: []
```
and the security definitions is:
```
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/saasbcn-98ce0"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "saasbcn-98ce0"
```

Thx
Victor
