### ISSUE TITLE
Access tokens in cookies

### ISSUE THREAD

**Issue by husseyd** [GoogleCloudPlatform/esp-v2#669]
I am using a JS SPA frontend which talks to the API backend via Endpoints (ESPv2) on Cloud Run. ESPv2 invokes the Cloud Run backend via native GCP IAM. This all goes through a load balancer that routes by path, so the domain is common to all components from the end user's perspective.

The frontend directs an anauthenticated user to login to Azure AD and receives a token back. For the frontend to allow the user to get a request through ESPv2, the token needs to be in an HTTP header ('Authorization: ' as usual).

But this requires that on the user end the token is stored in the browser's localStorage (or sessionStorage). We want to store the token in cookies so that we can set httpOnly, secure and sameSite flags.

Is there a way (or could a way be created) for ESPv2 to _instead_ parse the cookies to look for a token in particular cookie key?

EG I'm thinking extended x-google-jwt-locations to something like below

``` 
      x-google-jwt-locations:
        - header: "Cookie"
          value_prefix: "Bearer "
          cookie-key: "auth._token.aad"
```

Which would find the JWT token in amongst the below (shortened, redacted) sample cookies)
```
auth._token.aad=Bearer%20<JWT-TOKEN-HERE>; auth._token_expiration.aad=1646369191000; auth.strategy=aadAP
```
