### ISSUE TITLE
How to do API versioning  for APIs having the Cloud Function backends.

### ISSUE THREAD

**Issue by AbhishekgowdaSC** [GoogleCloudPlatform/esp-v2#735]
We need to do API versioning for the API having the  multiple Cloud Function backends. Since we are using multiple cloud functions we can not specify the version in base path in open api config . Need something like we need to send the api version number from the headers and validate, but not sure how exactly we can do it can some one  help on this?

**Comment by qiwzhang** [comment]
You may need to use version prefix in your path. e.g. "/v1/path", "/v2/path".   In your OpenAPI spec,  you can specify the `x-google-backend` at operation level.  Similar to this [example](https://github.com/GoogleCloudPlatform/esp-v2/blob/1777b9a49cf891f95d16d07d34eaf8616f6bf316/examples/dynamic_routing/openapi_swagger.json#L44). 

Something like:
```
paths:
   /v1/path:
      get:
          x-google-backend:
              address: v1_backend_cloud_function

```

You may have to use [path_translation](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#path_translation) to translate the path
