### ISSUE TITLE
ESPv2 not respecting the terminate signal

### ISSUE THREAD

**Issue by davidgwps** [GoogleCloudPlatform/esp-v2#743]
Hey, 

How do I gracefully shutdown a ESPv2 container? It doesn't seem that SIGTERM is being listened to.

I have just migrated from using ESP to ESPv2, and running into a problem whilst doing a rolling upgrade of a pod where the terminating pod stays stuck in a terminating state until the graceful shutdown period elapses and kubernetes kills it a few minutes later.

I've run the pod with and without the ESPv2 container, and this only happens with ESPv2 enabled and running locally in minikube or in GKE.

```yaml
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:2
          imagePullPolicy: Always
          args: [
            "--listener_port=8083",
            "--backend=127.0.0.1:8080",
            {{- if eq .Values.k8s.minikube.enabled false }}
            "--service={{ .Values.cloudEndpoints.hostName }}",
            "--rollout_strategy=managed",
            {{- else }}
            "--service_json_path=/etc/espv2_config/service_config.json",
            "--non_gcp",
            "--enable_debug",
            {{- end }}
          ]
          ports:
            - containerPort: 8083
          {{- if .Values.k8s.minikube.enabled }}
          volumeMounts:
            - mountPath: /etc/espv2_config
              name: service-config-volume
          {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8083
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8083
```

The debug logs in the ESPv2 container keep on churning out constantly, also indicating it is still running

[scratch.txt](https://github.com/GoogleCloudPlatform/esp-v2/files/9767240/scratch.txt)

kubes pod events showing that the container is attempted to be killed

```
│   Normal   Created    27m                kubelet            Created container esp                                                                                                                                                                        │
│   Normal   Started    27m                kubelet            Started container esp 
│   Normal   Created    27m                kubelet            Created container my_container                                                                                                                                                                   │
│   Normal   Started    27m                kubelet            Started container my_container                                                                                                                                                                   │
│   Warning  Unhealthy  27m (x2 over 27m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503                                                                                                                               │
│   Normal   Killing    3s                 kubelet            Stopping container esp                                                                                                                                                                       │
│   Normal   Killing    3s                 kubelet            Stopping container my_container 
```

Any help appreciated,
David
