### ISSUE TITLE
Is it possible to use endpoints-runtime:2 with cloud run

### ISSUE THREAD

**Issue by RTae** [GoogleCloudPlatform/esp-v2#883]
The reason that endpoints-runtime-serverless require a build image, and it doesn't suit my setup. In my project, I used GKE and ESPv2 to share my k8s workload which I think Is it possible to share the same ingress from ESP with a cloud run rather than using another cloud run as a proxy.

**Comment by timburks** [comment]
I've been experimenting with using Cloud Run sidecars to run ESPv2 with great results.

See https://github.com/apigee-apihub-demo/animals/pull/20

**Comment by RTae** [comment]
@timburks Cool, trick using cloud run side car as deployment. Actually, I already figured out how to solve my issue. Basically, add cloud run url as backend ( **x-google-backend** ) with **loadbalancer_ip** into backend **x-google-endpoints**

```yaml
x-google-endpoints:
- name: "${var.name}-${random_string.random.result}.endpoints.${var.project_id}.cloud.goog"
  target: "${var.loadbalancer_ip}"
  allowCors: True
x-google-backend:
    address: ${var.run_url}
    protocol: h2
```
